apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
spec:
  parentRefs:
  - name: pod-gateway
    sectionName: https-listener
    kind: Gateway
    namespace: projectcontour
  hostnames:
  - "argocd.pod.nvtc.io"
  rules:
  - backendRefs:
    - name: argocd-server
      port: 80